//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitaDiet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COCINASet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COCINASet()
        {
            this.COCINERO = new HashSet<COCINERO>();
        }
    
        public int Id { get; set; }
        public string UBICACION { get; set; }
        public string RUTAID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COCINERO> COCINERO { get; set; }
        public virtual RUTA RUTA { get; set; }
    }
}
