//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitaDiet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRIBUIDOR
    {
        public string ID { get; set; }
        public Nullable<int> CEDULA_NUTRICIONISTA { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string CELULAR { get; set; }
        public string CORREO { get; set; }
    }
}
