//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitaDiet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUTRICIONISTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NUTRICIONISTA()
        {
            this.CHEQUEO = new HashSet<CHEQUEO>();
        }
    
        public string ID { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public Nullable<int> CEDULA_NUTRICIONISTA { get; set; }
        public Nullable<int> TARJETA_PROFESIONAL { get; set; }
        public string GENERO { get; set; }
        public string CELULAR { get; set; }
        public string CORREO { get; set; }
        public string IDUSUARIO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHEQUEO> CHEQUEO { get; set; }
    }
}
