//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitaDiet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO { get; set; }
        public Nullable<int> TOTAL_PAGO { get; set; }
        public Nullable<int> ABONO { get; set; }
        public string IDPACIENTE { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
