//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitaDiet.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class COCINERO
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string CEDULA { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public string CIUDAD { get; set; }
        public string GENERO { get; set; }
        public string TELEFONO { get; set; }
        public string USUARIOID { get; set; }
        public int COCINAId { get; set; }
    
        public virtual COCINASet COCINASet { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
