//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitaDiet.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PACIENTE()
        {
            this.HISTORIAL = new HashSet<HISTORIAL>();
            this.CHEQUEO = new HashSet<CHEQUEO>();
            this.PQR = new HashSet<PQR>();
        }
    
        public string ID { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public Nullable<int> CEDULA_PACIENTE { get; set; }
        public string GENERO { get; set; }
        public string RH { get; set; }
        public string DOMICILIO { get; set; }
        public string OBJETIVOS { get; set; }
        public string TIEMPO_ESPERADO { get; set; }
        public string CELULAR { get; set; }
        public string CORREO { get; set; }
        public string USUARIO_ID { get; set; }
        public string DIETA_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL> HISTORIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHEQUEO> CHEQUEO { get; set; }
        public virtual DIETA DIETA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PQR> PQR { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
