//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitaDiet.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RUTA()
        {
            this.COCINASet = new HashSet<COCINASet>();
        }
    
        public string ID { get; set; }
        public string DESTINOS { get; set; }
        public string COCINAS { get; set; }
        public string DISTRIBUIDORID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COCINASet> COCINASet { get; set; }
        public virtual DISTRIBUIDOR DISTRIBUIDOR { get; set; }
    }
}
